config/routes.rb
Rails.application.routes.draw do
  resources :contaminantes
  get 'welcome/index'

  root 'welcome#index'
  resources :lugares
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contaminante.rb
class Contaminante < ApplicationRecord
  
end

app/models/lugare.rb
class Lugare < ApplicationRecord
    
    def self.search(search)
        # Title is for the above case, the OP incorrectly had 'name'
        where("nombre ILIKE ? or descripcion ILIKE ?", "%#{search}%", "%#{search}%")
    end

    def peligrosidad
        mpr = self.cont_v1
        dioxidoazufre = self.cont_v2
        monoxidocarb = self.cont_v3
        dioxidonitrogeno = self.cont_v4
        ozono = self.cont_v5

        if (mpr >= 355  ) && (dioxidoazufre >= 812.2 ) &6
            (monoxidocarb > 17800 ) && (dioxidonitrogeno > 1222) && 
            (ozono > 402)
            return 3
        elsif ( mpr < 150) && (dioxidoazufre < 365 ) && (monoxidocarb < 10000) && 
            (dioxidonitrogeno < 150) && (ozono <235)
            return 1
        else
            return 2 
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contaminantes_controller.rb
class ContaminantesController < ApplicationController
  before_action :set_contaminante, only: [:show, :edit, :update, :destroy]

  # GET /contaminantes
  # GET /contaminantes.json
  def index
    @contaminantes = Contaminante.all
  end

  # GET /contaminantes/1
  # GET /contaminantes/1.json
  def show
  end

  # GET /contaminantes/new
  def new
    @contaminante = Contaminante.new
  end

  # GET /contaminantes/1/edit
  def edit
  end

  # POST /contaminantes
  # POST /contaminantes.json
  def create
    @contaminante = Contaminante.new(contaminante_params)

    respond_to do |format|
      if @contaminante.save
        format.html { redirect_to @contaminante, notice: 'Contaminante was successfully created.' }
        format.json { render :show, status: :created, location: @contaminante }
      else
        format.html { render :new }
        format.json { render json: @contaminante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contaminantes/1
  # PATCH/PUT /contaminantes/1.json
  def update
    respond_to do |format|
      if @contaminante.update(contaminante_params)
        format.html { redirect_to @contaminante, notice: 'Contaminante was successfully updated.' }
        format.json { render :show, status: :ok, location: @contaminante }
      else
        format.html { render :edit }
        format.json { render json: @contaminante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contaminantes/1
  # DELETE /contaminantes/1.json
  def destroy
    @contaminante.destroy
    respond_to do |format|
      format.html { redirect_to contaminantes_url, notice: 'Contaminante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contaminante
      @contaminante = Contaminante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contaminante_params
      params.require(:contaminante).permit(:nombre, :descripcion, :nivel, :lugare_id)
    end
end

app/controllers/lugares_controller.rb
class LugaresController < ApplicationController
  before_action :set_lugare, only: [:show, :edit, :update, :destroy]
  before_action :require_admin_params!, only: [:new, :edit, :create, :update,  :destroy]
  # GET /lugares
  # GET /lugares.json
  def index
    if params[:search]
      @lugares = Lugare.search(params[:search]).order("created_at DESC").page(params[:page]).per(5)
    else
      @lugares = Lugare.order('created_at DESC').page(params[:page]).per(5)
    end
  end

  # GET /lugares/1
  # GET /lugares/1.json
  def show
  end

  # GET /lugares/new
  def new
    @lugare = Lugare.new
  end

  # GET /lugares/1/edit
  def edit
  end

  # POST /lugares
  # POST /lugares.json
  def create
    @lugare = Lugare.new(lugare_params)

    respond_to do |format|
      if @lugare.save
        format.html { redirect_to @lugare, notice: 'Lugare was successfully created.' }
        format.json { render :show, status: :created, location: @lugare }
      else
        format.html { render :new }
        format.json { render json: @lugare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugares/1
  # PATCH/PUT /lugares/1.json
  def update
    respond_to do |format|
      if @lugare.update(lugare_params)
        format.html { redirect_to @lugare, notice: 'Lugare was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugare }
      else
        format.html { render :edit }
        format.json { render json: @lugare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugares/1
  # DELETE /lugares/1.json
  def destroy
    @lugare.destroy
    respond_to do |format|
      format.html { redirect_to lugares_url, notice: 'Lugare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def require_admin_params!
      if user_signed_in?
        unless current_user.admin == true
            redirect_to root_path, status: 401
        end
      else
        false
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_lugare
      @lugare = Lugare.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lugare_params
      params.require(:lugare).permit(:nombre, :descripcion, :cont_n1, :cont_v1, :cont_n2, :cont_v2, :cont_n3, :cont_v3, :cont_n4, :cont_v4, :cont_n5, :cont_v5)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:search]
      @lugares = Lugare.search(params[:search]).order("created_at DESC").page(params[:page]).per(5)
    else
      @lugares = Lugare.order('created_at DESC').page(params[:page]).per(5)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contaminantes_helper.rb
module ContaminantesHelper
end

app/helpers/lugares_helper.rb
module LugaresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contaminantes/_form.html.erb
<%= form_with(model: contaminante, local: true) do |form| %>
  <% if contaminante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contaminante.errors.count, "error") %> prohibited this contaminante from being saved:</h2>

      <ul>
        <% contaminante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :nivel %>
    <%= form.text_field :nivel %>
  </div>

  <div class="field">
    <%= form.label :lugare_id %>
    <%= form.text_field :lugare_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contaminantes/edit.html.erb
<h1>Editing Contaminante</h1>

<%= render 'form', contaminante: @contaminante %>

<%= link_to 'Show', @contaminante %> |
<%= link_to 'Back', contaminantes_path %>

app/views/contaminantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contaminantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Nivel</th>
      <th>Lugare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contaminantes.each do |contaminante| %>
      <tr>
        <td><%= contaminante.nombre %></td>
        <td><%= contaminante.descripcion %></td>
        <td><%= contaminante.nivel %></td>
        <td><%= contaminante.lugare_id %></td>
        <td><%= link_to 'Show', contaminante %></td>
        <td><%= link_to 'Edit', edit_contaminante_path(contaminante) %></td>
        <td><%= link_to 'Destroy', contaminante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contaminante', new_contaminante_path %>

app/views/contaminantes/new.html.erb
<h1>New Contaminante</h1>

<%= render 'form', contaminante: @contaminante %>

<%= link_to 'Back', contaminantes_path %>

app/views/contaminantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @contaminante.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @contaminante.descripcion %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @contaminante.nivel %>
</p>

<p>
  <strong>Lugare:</strong>
  <%= @contaminante.lugare_id %>
</p>

<%= link_to 'Edit', edit_contaminante_path(@contaminante) %> |
<%= link_to 'Back', contaminantes_path %>

app/views/layouts/_footer.html.erb
<!--Footer Start-->
         <footer class="footer">
            <div class="footer-top wf100">
               <div class="container">
                  <div class="row">
                     <div class="col-lg-3 col-md-6 col-sm-6">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <h4>Acerca de nosotros</h4>
                           <p> Somos un equipo de estudiantes de la UTP, con el objetivo de orientar a las personas sobre el estado del medio ambiente, dispuestos a hacer un cambio en la sociedad, todo esto sin ánimos de lucro. </p>
                           <a href="#" class="lm">Contactar</a> 
                        </div>
                        <!--Footer Widget End--> 
                     </div>
                     <div class="col-lg-3 col-md-6 col-sm-6">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <h4>Nuestras Promesas</h4>
                           <ul class="quick-links">
                              <li><a href="#">Brindar información confiable</a></li>
                              <li><a href="#">Ayudar a tu comunidad</a></li>
                              <li><a href="#">Eco Ideas</a></li>
                              <li><a href="#">Jornadas de reciclaje</a></li>
                              <li><a href="#">Plantar árboles</a></li>
                              <li><a href="#">Proteger la vida silvestre </a></li>
                           </ul>
                        </div>
                        <!--Footer Widget End--> 
                     </div>
                     <div class="col-lg-3 col-md-6 col-sm-6">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <h4>Artículos Recientes</h4>
                           <ul class="lastest-products">
                              <li> <img src="images/flp1.jpg" alt=""> <strong><a href="#">¿Cómo puedes mantener vivos a los animales salvajes?...</a></strong> <span class="pdate"><i>Publicado:</i> 21 de Octubre, 2020</span> </li>
                              <li> <img src="images/flp2.jpg" alt=""> <strong><a href="#">Elimine la contaminación de su botella de plástico y mantenga...</a></strong> <span class="pdate"><i>Publicado:</i> 5 de Octubre, 2020</span> </li>
                              <li> <img src="images/flp3.jpg" alt=""> <strong><a href="#">¿Cómo puedo mantener limpia mi comunidad?...</a></strong> <span class="pdate"><i>Publicado:</i> 29 de Septiembre, 2020</span> </li>
                           </ul>
                        </div>
                        <!--Footer Widget End--> 
                     </div>
                     <div class="col-lg-3 col-md-6 col-sm-6">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <div id="fpro-slider" class="owl-carousel owl-theme">
                              <!--Footer Product Start-->
                              <div class="item">
                                 <div class="f-product">
                                    <img src="images/fpro1.jpg" alt="">
                                    <div class="fp-text">
                                       <h6><a href="#">Buy T-Shirts</a></h6>
                                       <strong>$19.00</strong> 
                                    </div>
                                 </div>
                              </div>
                              <!--Footer Product End--> 
                              <!--Footer Product Start-->
                              <div class="item">
                                 <div class="f-product">
                                    <img src="images/fpro1.jpg" alt="">
                                    <div class="fp-text">
                                       <h6><a href="#">Buy T-Shirts</a></h6>
                                       <strong>$19.00</strong> 
                                    </div>
                                 </div>
                              </div>
                              <!--Footer Product End--> 
                              <!--Footer Product Start-->
                              <div class="item">
                                 <div class="f-product">
                                    <img src="images/fpro1.jpg" alt="">
                                    <div class="fp-text">
                                       <h6><a href="#">Buy T-Shirts</a></h6>
                                       <strong>$19.00</strong> 
                                    </div>
                                 </div>
                              </div>
                              <!--Footer Product End--> 
                           </div>
                        </div>
                        <!--Footer Widget End--> 
                     </div>
                  </div>
               </div>
            </div>
            <div class="footer-copyr wf100">
               <div class="container">
                  <div class="row">
                     <div class="col-md-4 col-sm-4"> <img src="images/logo.png" alt=""> </div>
                     <div class="col-md-8 col-sm-8">
                        <p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
                     </div>
                  </div>
               </div>
            </div>
         </footer>
         <!--Footer End--> 

app/views/layouts/_navigation.html.erb
<!--Header Start-->
         <header class="header-style-2">
            <nav class="navbar navbar-expand-lg">
               <a class="navbar-brand" href="index-2.html"><img src="images/h2logo.png" alt=""></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <i class="fas fa-bars"></i> </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item dropdown">
                         <%= link_to 'Inicio', root_path, :class=>"nav-link" %>
                     </li>
                     <li class="nav-item"> <%= link_to 'Destinos', root_path, :class=>"nav-link" %> </li>
                     
                     <li class="nav-item dropdown">
                        <%= link_to 'Nosotros', root_path, :class=>"nav-link" %>
                     </li>
                     

                  <% if user_signed_in?  %>
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                              <i class="fa fa-user mr-1"></i><%= current_user.email %>
                        </a>
                              
                        <div class="dropdown-menu dropdown-menu-right dropdown-default"
                              aria-labelledby="navbarDropdownMenuLink-333">
                              <%= link_to('Editar perfil', edit_user_registration_path,  :class=>"dropdown-item") %>
                              <%= link_to('Panel de Administrador', root_path,  :class=>"dropdown-item") %>
                        <div class="dropdown-divider"></div>
                              <%= link_to('Cerrar Sesión', destroy_user_session_path, method: :delete,  :class=>"dropdown-item") %>
                        </div>
                     </li>
                  <% elsif user_signed_in? %>
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                              <i class="fa fa-user mr-1"></i><%= current_user.email %>
                        </a>
                              
                        <div class="dropdown-menu dropdown-menu-right dropdown-default"
                              aria-labelledby="navbarDropdownMenuLink-333">
                              <%= link_to('Editar perfil', edit_user_registration_path,  :class=>"dropdown-item") %>
                        
                        <div class="dropdown-divider"></div>
                              <%= link_to('Cerrar Sesión', destroy_user_session_path, method: :delete,  :class=>"dropdown-item") %>
                        </div>
                     </li>
                  <% else %>
                     <li class="nav-item mt-2">
                        <%= link_to 'Registrarse', new_user_registration_path , :class=>"btn btn-outline-success ml-2 mr-2 mb-n4 text-white"%>
                     </li>
                     <li class="nav-item mt-2">
                        <%= link_to 'Iniciar Sesión', new_user_session_path , :class=>"btn btn-success ml-2 mr-2 mb-n4"%>
                     </li>
                  <% end %>
                      
                  </ul>
                  <ul class="topnav-right">
                     <li> <a class="mdonate" href="donation.html"><span>Make a Donation</span></a> </li>
                     <li> <a class="search-icon" href="#search"> <i class="fas fa-search"></i> </a> </li>
                     <li class="dropdown">
                        <a class="cart-icon" href="#" role="button" id="cartdropdown" data-toggle="dropdown"> <i class="fas fa-shopping-cart"></i></a>
                        <div class="dropdown-menu cart-box" aria-labelledby="cartdropdown">
                           Recently added item(s)
                           <ul class="list">
                              <li class="item">
                                 <a href="#" class="preview-image"><img class="preview" src="bthed/images/pro.jpg" alt=""></a>
                                 <div class="description"> <a href="#">Sample Course</a> <strong class="price">1 x $44.95</strong> </div>
                              </li>
                              <li class="item">
                                 <a href="#" class="preview-image"><img class="preview" src="bthed/images/pro.jpg" alt=""></a>
                                 <div class="description"> <a href="#">Sample Course</a> <strong class="price">1 x $44.95</strong> </div>
                              </li>
                           </ul>
                           <div class="total">Total: <strong>$44.95</strong></div>
                           <div class="view-link"><a href="#">Proceed to Checkout</a> <a href="#">View cart </a></div>
                        </div>
                     </li>
                     <li class="login-reg"> <a href="my-account.html">Login</a> | <a href="my-account.html">Signup</a> </li>
                  </ul>
               </div>
            </nav>
         </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IngAmbiental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS FILES START -->
    <link href="bthed/css/custom.css" rel="stylesheet">
    <link href="bthed/css/color.css" rel="stylesheet">
    <link href="bthed/css/responsive.css" rel="stylesheet">
    <link href="bthed/css/owl.carousel.min.css" rel="stylesheet">
    <link href="bthed/css/bootstrap.min.css" rel="stylesheet">
    <link href="bthed/css/prettyPhoto.css" rel="stylesheet">
    <link href="bthed/css/all.min.css" rel="stylesheet">
    <!-- CSS FILES End -->
  <!--   JS Files Start  --> 
    <script src="bthed/js/jquery-3.3.1.min.js"></script> 
    <script src="bthed/js/jquery-migrate-1.4.1.min.js"></script> 
    <script src="bthed/js/popper.min.js"></script> 
    <script src="bthed/js/bootstrap.min.js"></script> 
    <script src="bthed/js/owl.carousel.min.js"></script> 
    <script src="bthed/js/jquery.prettyPhoto.js"></script> 
    <script src="bthed/js/isotope.min.js"></script> 
    <script src="bthed/js/custom.js"></script>
  </head>

  <body>
    <% if devise_controller? %>
      <%= yield %>
    <% else %>
      <%= render 'layouts/navigation' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/lugares/edit.html.erb
 <!-- CSS FILES START -->
    <link href="../../bthed/css/custom.css" rel="stylesheet">
    <link href="../../bthed/css/color.css" rel="stylesheet">
    <link href="../../bthed/css/responsive.css" rel="stylesheet">
    <link href="../../bthed/css/owl.carousel.min.css" rel="stylesheet">
    <link href="../../bthed/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../bthed/css/prettyPhoto.css" rel="stylesheet">
    <link href="../../bthed/css/all.min.css" rel="stylesheet">
    <!-- CSS FILES End -->
  <!--   JS Files Start  --> 

<h1 class="h1 text-center">Edición</h1>

<%= render 'form', lugare: @lugare %>

<%= link_to 'Show', @lugare %> |
<%= link_to 'Back', lugares_path %>

app/views/lugares/index.html.erb
<h1 class="text-center h1">Lugares</h1>
<div class="text-center">
  <div class="form-group ml-5 mr-5 ">
      <div class="row d-flex justify-content-center">
          <%= form_tag(lugares_path, :method => "get", class: "mx-auto") do %>
            <div class="d-flex justify-content-center">
                <h5 class="text-dark text-nowrap mr-3" >Haz tu Búsqueda:</h5>
                <%= text_field_tag :search, params[:search], placeholder: "Buscar Destinos...",:id => "query", :class=>"form-control" %>
                <%= submit_tag("Buscar", :class=>"btn btn-success text-wrap ml-2") %>
            </div>
          <% end %>
      </div>
  </div>
</div>
<div class="container">
  <div class="text-center">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripción</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @lugares.each do |lugare| %>
          <tr>
            <td><%= lugare.nombre %></td>
            <td><%= lugare.descripcion %></td>
            <td><%= link_to 'Mostrar', lugare, class: 'btn btn-info' %></td>
            <td><%= link_to 'Editar', edit_lugare_path(lugare), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Destroy', lugare, class: 'btn btn-danger',method: :delete, data: { confirm: 'Esta seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @lugares%>
    <br>
    <%= link_to 'Añadir nuevo destino', new_lugare_path, class: 'btn btn-success mb-5' %>
  </div>
</div>

app/views/lugares/new.html.erb
 <!-- CSS FILES START -->
    <link href="../../bthed/css/custom.css" rel="stylesheet">
    <link href="../../bthed/css/color.css" rel="stylesheet">
    <link href="../../bthed/css/responsive.css" rel="stylesheet">
    <link href="../../bthed/css/owl.carousel.min.css" rel="stylesheet">
    <link href="../../bthed/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../bthed/css/prettyPhoto.css" rel="stylesheet">
    <link href="../../bthed/css/all.min.css" rel="stylesheet">
    <!-- CSS FILES End -->
  <!--   JS Files Start  --> 
<div class="container text-center">
<h1 class="text-center h1">Añadir Destino</h1>
<%= render 'form', lugare: @lugare %>

<%= link_to 'Regresar', lugares_path, class: 'btn btn-warning' %>
</div>

app/views/lugares/show.html.erb
 <!-- CSS FILES START -->
    <link href="../bthed/css/custom.css" rel="stylesheet">
    <link href="../bthed/css/color.css" rel="stylesheet">
    <link href="../bthed/css/responsive.css" rel="stylesheet">
    <link href="../bthed/css/owl.carousel.min.css" rel="stylesheet">
    <link href="../bthed/css/bootstrap.min.css" rel="stylesheet">
    <link href="../bthed/css/prettyPhoto.css" rel="stylesheet">
    <link href="../bthed/css/all.min.css" rel="stylesheet">
    <!-- CSS FILES End -->
  <!--   JS Files Start  --> 
    <script src="../bthed/js/jquery-3.3.1.min.js"></script> 
    <script src="../bthed/js/jquery-migrate-1.4.1.min.js"></script> 
    <script src="../bthed/js/popper.min.js"></script> 
    <script src="../bthed/js/bootstrap.min.js"></script> 
    <script src="../bthed/js/owl.carousel.min.js"></script> 
    <script src="../bthed/js/jquery.prettyPhoto.js"></script> 
    <script src="../bthed/js/isotope.min.js"></script> 
    <script src="../bthed/js/custom.js"></script>
<p id="notice"><%= notice %></p>

<h2 class="text-center">
  <strong>Destino:</strong>
  <%= @lugare.nombre if not @lugare.nombre.nil? %>
</h2>
<br><br>
<h5 class="text-left text-justify ml-5 pl-5">
  <strong>Descripción:</strong>
  <%= @lugare.descripcion if not @lugare.descripcion.nil? %>
</h5>
<br><br>
<% if @lugare.peligrosidad == 1  %>
<h5 class="text-left text-justify ml-5 pl-5">
  <strong>Nivel de Polución:</strong>
  <div class="alert alert-success" role="alert">
    ¡El estado de calidad del aire es óptimo!
  </div>
</h5>
<% elsif @lugare.peligrosidad == 2  %>
<h5 class="text-left text-justify ml-5 pl-5">
  <strong>Nivel de Polución:</strong>
  <div class="alert alert-warning" role="alert">
    ¡El estado de calidad del aire es regular!
  </div>
</h5>
<% elsif @lugare.peligrosidad == 3  %>
<h5 class="text-left text-justify ml-5 pl-5">
  <strong>Nivel de Polución:</strong>
  <div class="alert alert-danger" role="alert">
    ¡Peligro, El estado de calidad del aire puede ser perjudicial para su salud!
  </div>
</h5>
<% end  %>
<br><br>
<div class="text-center">
  <%= image_tag 'ecology.jpg' %>
</div>

<div class="container mb-5">
  <% if user_signed_in?  %>
    <%= link_to 'Editar', edit_lugare_path(@lugare), class: "btn btn-warning" %> |
  <% end  %>
  <%= link_to 'Regresar', root_path, class: "btn btn-primary" %>
</div>